AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AppSync Lambda functions for obwWebApp

Globals:
  Function:
    Timeout: 30
    Runtime: python3.13
    Architectures:
      - x86_64

Parameters:
  SendGridApiKey:
    Type: String
    Description: "SendGrid API Key"
    NoEcho: true

Resources:
  # S3バケットの作成
  PassportUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "privacy-obw-id-upload"
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - http://localhost:5173 # テスト終わったら削除
              - https://app.osakabaywheel.com
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - ETag
            MaxAge: 3000

  # 署名付きURL用Lambda
  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-get-presigned-url-function
      MemorySize: 128
      CodeUri: lambda_functions/get_presigned_url/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 30
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref PassportUploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref PassportUploadBucket
        - S3ReadPolicy:
            BucketName: !Ref PassportUploadBucket

  RequestAccessFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: obw-request-access-function
      Handler: lambda_handler_request_access.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128
      CodeUri: lambda_functions/request_access/
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
          SENDGRID_API_KEY: !Ref SendGridApiKey
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: "*"

  VerifyAccessTokenFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: obw-verify-access-token-function
      Handler: lambda_handler_verify_access.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128
      CodeUri: lambda_functions/verify_access/
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - DynamoDBWritePolicy:
            TableName: !ImportValue Obw-GuestTableName

  AdminApproveGuestFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: obw-admin-approve-guest-function
      CodeUri: lambda_functions/admin_approve_guest/
      Handler: lambda_handler_admin_approve_guest.lambda_handler
      Runtime: python3.13
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - DynamoDBWritePolicy:
            TableName: !ImportValue Obw-GuestTableName

  TransferRoomGuestsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-transfer-room-guests-function
      MemorySize: 256
      CodeUri: lambda_functions/transfer_room_guests/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
          SENDGRID_API_KEY: !Ref SendGridApiKey
          APP_BASE_URL: "https://app.osakabaywheel.com"
          MAIL_FROM: "osakabaywheel4224@gmail.com"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: "*"

Outputs:
  PassportUploadBucketName:
    Description: "S3 bucket for passport uploads"
    Value: !Ref PassportUploadBucket
  RequestAccessFunctionArn:
    Description: "ARN for request-access Lambda"
    Value: !GetAtt RequestAccessFunction.Arn
    Export:
      Name: Obw-RequestAccessFunctionArn
  VerifyAccessTokenFunctionArn:
    Description: "ARN for verify-access-token Lambda"
    Value: !GetAtt VerifyAccessTokenFunction.Arn
    Export:
      Name: Obw-VerifyAccessTokenFunctionArn
  GetPresignedUrlFunctionArn:
    Description: "ARN for GetPresignedUrl Lambda"
    Value: !GetAtt GetPresignedUrlFunction.Arn
    Export:
      Name: Obw-GetPresignedUrlFunctionArn
  AdminApproveGuestFunctionArn:
    Description: "ARN for admin-approve-guest Lambda"
    Value: !GetAtt AdminApproveGuestFunction.Arn
    Export:
      Name: Obw-AdminApproveGuestFunctionArn
  TransferRoomGuestsFunctionArn:
    Description: "ARN for transfer-room-guests Lambda"
    Value: !GetAtt TransferRoomGuestsFunction.Arn
    Export:
      Name: Obw-TransferRoomGuestsFunctionArn