AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AppSync Lambda functions for obwWebApp

Parameters:
  SmtpUser:
    Type: String
    Description: "Zoho SMTP User (email address)"
    NoEcho: true
  SmtpPassword:
    Type: String
    Description: "Zoho SMTP Password"
    NoEcho: true

Resources:
  # S3バケットの作成
  PassportUploadBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: privacy-obw-id-upload
      # KMS暗号化を有効化（AWS managed key使用）
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: aws:kms
              # KMSMasterKeyIDを指定しない = AWS managed key (aws/s3) を使用
            BucketKeyEnabled: true  # S3 Bucket Keyでコスト削減
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteAfter3Years
            Status: Enabled
            ExpirationInDays: 1095
          - Id: ArchiveOldBackups
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: GLACIER
      CorsConfiguration:
        CorsRules:
          - AllowedOrigins:
              - http://localhost:5173 # テスト終わったら削除
              - https://app.osakabaywheel.com
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedHeaders:
              - "*"
            ExposedHeaders:
              - ETag
            MaxAge: 3000
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  # CloudWatch Logs - GetPresignedUrlFunction
  GetPresignedUrlFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/obw-get-presigned-url-function
      RetentionInDays: 365

  # CloudWatch Logs - RequestAccessFunction
  RequestAccessFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/obw-request-access-function
      RetentionInDays: 365

  # CloudWatch Logs - VerifyAccessTokenFunction
  VerifyAccessTokenFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/obw-verify-access-token-function
      RetentionInDays: 365

  # CloudWatch Logs - AdminApproveGuestFunction
  AdminApproveGuestFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/obw-admin-approve-guest-function
      RetentionInDays: 365

  # CloudWatch Logs - TransferRoomGuestsFunction
  TransferRoomGuestsFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/obw-transfer-room-guests-function
      RetentionInDays: 365

  # 署名付きURL用Lambda
  GetPresignedUrlFunction:
    Type: AWS::Serverless::Function
    DependsOn: GetPresignedUrlFunctionLogGroup
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-get-presigned-url-function
      MemorySize: 128
      CodeUri: lambda_functions/get_presigned_url/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 30
      Environment:
        Variables:
          UPLOAD_BUCKET: !Ref PassportUploadBucket
      Policies:
        - S3WritePolicy:
            BucketName: !Ref PassportUploadBucket
        - S3ReadPolicy:
            BucketName: !Ref PassportUploadBucket

  RequestAccessFunction:
    Type: AWS::Serverless::Function
    DependsOn: RequestAccessFunctionLogGroup
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-request-access-function
      MemorySize: 128
      CodeUri: lambda_functions/request_access/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
          SMTP_USER: !Ref SmtpUser
          SMTP_PASSWORD: !Ref SmtpPassword
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: "*"

  VerifyAccessTokenFunction:
    Type: AWS::Serverless::Function
    DependsOn: VerifyAccessTokenFunctionLogGroup
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-verify-access-token-function
      MemorySize: 128
      CodeUri: lambda_functions/verify_access_token/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - DynamoDBWritePolicy:
            TableName: !ImportValue Obw-GuestTableName

  AdminApproveGuestFunction:
    Type: AWS::Serverless::Function
    DependsOn: AdminApproveGuestFunctionLogGroup
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-admin-approve-guest-function
      MemorySize: 128
      CodeUri: lambda_functions/admin_approve_guest/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 30
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
      Policies:
        - DynamoDBReadPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - DynamoDBWritePolicy:
            TableName: !ImportValue Obw-GuestTableName

  TransferRoomGuestsFunction:
    Type: AWS::Serverless::Function
    DependsOn: TransferRoomGuestsFunctionLogGroup
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-transfer-room-guests-function
      MemorySize: 256
      CodeUri: lambda_functions/transfer_room_guests/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 60
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
          SMTP_USER: !Ref SmtpUser
          SMTP_PASSWORD: !Ref SmtpPassword
          APP_BASE_URL: "https://app.osakabaywheel.com"
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Obw-GuestTableName
        - Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: "*"

Outputs:
  PassportUploadBucketName:
    Description: "S3 bucket for passport uploads"
    Value: !Ref PassportUploadBucket
  RequestAccessFunctionArn:
    Description: "ARN for request-access Lambda"
    Value: !GetAtt RequestAccessFunction.Arn
    Export:
      Name: Obw-RequestAccessFunctionArn
  VerifyAccessTokenFunctionArn:
    Description: "ARN for verify-access-token Lambda"
    Value: !GetAtt VerifyAccessTokenFunction.Arn
    Export:
      Name: Obw-VerifyAccessTokenFunctionArn
  GetPresignedUrlFunctionArn:
    Description: "ARN for GetPresignedUrl Lambda"
    Value: !GetAtt GetPresignedUrlFunction.Arn
    Export:
      Name: Obw-GetPresignedUrlFunctionArn
  AdminApproveGuestFunctionArn:
    Description: "ARN for admin-approve-guest Lambda"
    Value: !GetAtt AdminApproveGuestFunction.Arn
    Export:
      Name: Obw-AdminApproveGuestFunctionArn
  TransferRoomGuestsFunctionArn:
    Description: "ARN for transfer-room-guests Lambda"
    Value: !GetAtt TransferRoomGuestsFunction.Arn
    Export:
      Name: Obw-TransferRoomGuestsFunctionArn