AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Daily actions for obwWebApp

Resources:
  DailyRecordsCleanupFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: obw-daily-records-cleanup
      Runtime: python3.13
      Handler: daily_records_cleanup.lambda_handler
      CodeUri: lambda_functions/daily_records_cleanup/
      MemorySize: 256
      Timeout: 180
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Obw-GuestTableName
      Events:
        MidnightJSTTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(0 15 * * ? *)   # 00:00 JST (UTC+9)
            Name: obw-daily-records-cleanup-schedule
            Description: Run guest cleanup at 00:00 JST
            Enabled: true

Outputs:
  DailyRecordsCleanupFunctionArn:
    Value: !GetAtt DailyRecordsCleanupFunction.Arn
    Export:
      Name: DailyRecordsCleanupFunctionArn