AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Daily actions for obwWebApp

Resources:
  DailyRecordsCleanupFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: makefile
    Properties:
      FunctionName: obw-daily-records-cleanup
      MemorySize: 256
      CodeUri: lambda_functions/daily_records_cleanup/
      Handler: bootstrap
      Runtime: provided.al2023
      Timeout: 180
      Environment:
        Variables:
          TABLE_NAME: !ImportValue Obw-GuestTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !ImportValue Obw-GuestTableName
      Events:
        MidnightJSTTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(5 15 * * ? *)   # 00:05 JST (UTC+9)
            Name: obw-daily-records-cleanup-midnight
            Description: Run guest cleanup at 00:05 JST
            Enabled: true
        NoonJSTTrigger:
          Type: Schedule
          Properties:
            Schedule: cron(5 3 * * ? *)    # 12:05 JST (UTC+9)
            Name: obw-daily-records-cleanup-noon
            Description: Run guest cleanup at 12:05 JST
            Enabled: true

Outputs:
  DailyRecordsCleanupFunctionArn:
    Value: !GetAtt DailyRecordsCleanupFunction.Arn
    Export:
      Name: DailyRecordsCleanupFunctionArn