AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  obwWebApp
  AWS SAM/CloudFormation Template for obwWebApp

Globals:
  Function:
    Timeout: 30
    MemorySize: 1024
    Runtime: python3.13
    Architectures:
      - x86_64
    Layers:
      - !Ref LayerForObw # SAMでビルド・デプロイされるレイヤーを参照
      # - arn:aws:lambda:ap-northeast-1:028816703777:layer:layer_for_obw:6 # 特定の既存レイヤーバージョンを固定で使いたい場合は上記をコメントアウトし、こちらを有効化

Parameters:
  OpenAiApiKey:
    Type: String
    Description: "OpenAI API Key"
    NoEcho: true
  TwilioAccountSid:
    Type: String
    Description: "Twilio Account SID"
    NoEcho: true
  TwilioAuthToken:
    Type: String
    Description: "Twilio Auth Token"
    NoEcho: true
  AiProcessingLambdaFunctionName:
    Type: String
    Description: "Name of the AI Processing Lambda function"
    Default: "obw-ai-processing-function"
  # ImmediateResponseFunction の Function URL が Outputs から取得される場合、
  # 最初は空文字をデフォルトにすることでエラーを防ぎ、後続のパイプラインで上書き
  ImmediateResponseFunctionUrlParam:
    Type: String
    Description: "Function URL for Immediate Response, provided from Outputs"
    Default: ""

Resources:
  LayerForObw:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: layer_for_obw
      Description: Common libraries for obwWebApp (Twilio, OpenAI, etc.)
      ContentUri: layers/
      CompatibleRuntimes:
        - python3.13
      CompatibleArchitectures:
        - x86_64
      LicenseInfo: 'Available under the MIT license.'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: x86_64

  ImmediateResponseFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: obw-immediate-response-function
      CodeUri: lambda_functions/immediate-response/
      Handler: lambda_handler_immediate_response.lambda_handler
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: live
      FunctionUrlConfig:
        AuthType: NONE
        Cors:
          AllowOrigins: [ "*" ]
          AllowMethods: [ "POST" ]
          AllowHeaders: [ "Content-Type" ]
      Environment:
        Variables:
          AI_PROCESSING_LAMBDA_NAME: !Ref AiProcessingLambdaFunctionName
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref AiProcessingLambdaFunctionName

  AiProcessingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref AiProcessingLambdaFunctionName
      CodeUri: lambda_functions/ai_processing/
      Handler: lambda_handler_ai_processing.lambda_handler
      SnapStart:
        ApplyOn: PublishedVersions
      AutoPublishAlias: live
      Environment:
        Variables:
          OPENAI_API_KEY: !Ref OpenAiApiKey
          TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
          TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
          # ImmediateResponseFunction の Function URL は、Outputs から
          # 得た値をパラメータで渡すことを想定しています。
          LAMBDA1_FUNCTION_URL: !Ref ImmediateResponseFunctionUrlParam

Outputs:
  ImmediateResponseFunctionArn:
    Description: "ARN for Immediate Response function"
    Value: !GetAtt ImmediateResponseFunction.Arn
  AiProcessingFunctionArn:
    Description: "ARN for AI Processing function"
    Value: !GetAtt AiProcessingFunction.Arn