AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  EnableLambdaIntegration:
    Type: String
    AllowedValues: ["true", "false"]
    Default: "false"

Conditions:
  DoLambdaIntegration: !Equals [ !Ref EnableLambdaIntegration, "true" ]

Resources:
  AppSyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: GuestCheckinAPI
      AuthenticationType: AWS_IAM

  GuestTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: roomNumber
          AttributeType: S
        - AttributeName: guestId
          AttributeType: S
        - AttributeName: sessionTokenHash
          AttributeType: S
      KeySchema:
        - AttributeName: roomNumber
          KeyType: HASH
        - AttributeName: guestId
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: SessionTokenHashIndex
          KeySchema:
            - AttributeName: sessionTokenHash
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      TimeToLiveSpecification:
        AttributeName: pendingVerificationTtl
        Enabled: true
      TableName: guest

  AppSyncSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Definition: |
        type Guest {
          roomNumber: String!
          guestId: String!
          guestName: String!
          email: String!
          address: String!
          phone: String!
          occupation: String
          nationality: String!
          passportImageUrl: String
          checkInDate: AWSDate!
          checkOutDate: AWSDate!
          approvalStatus: String!
          promoConsent: Boolean!
          sessionTokenExpiresAt: AWSDateTime
          sessionTokenHash: String
          pendingVerificationTtl: AWSTimestamp
          contactChannel: String
          createdAt: AWSDateTime
          updatedAt: AWSDateTime
        }

        input CreateGuestInput {
          roomNumber: String!
          guestId: String!
          guestName: String!
          email: String!
          address: String!
          phone: String!
          occupation: String
          nationality: String!
          passportImageUrl: String
          checkInDate: AWSDate!
          checkOutDate: AWSDate!
          promoConsent: Boolean!
        }

        input UpdateGuestInput {
          roomNumber: String!
          guestId: String!
          guestName: String
          email: String
          address: String
          phone: String
          occupation: String
          nationality: String
          passportImageUrl: String
          checkInDate: AWSDate
          checkOutDate: AWSDate
          approvalStatus: String
          promoConsent: Boolean
          sessionTokenExpiresAt: AWSDateTime
          sessionTokenHash: String
          pendingVerificationTtl: AWSTimestamp
          contactChannel: String
        }

        input RequestAccessInput {
          roomNumber: String!
          guestName: String!
          email: String
          phone: String
        }

        type RequestAccessResult {
          success: Boolean!
          guestId: String!
        }

        type VerifyTokenResult {
          success: Boolean!
          guest: Guest
        }

        type Mutation {
          createGuest(input: CreateGuestInput!): Guest
          updateGuest(input: UpdateGuestInput!): Guest
          requestAccess(input: RequestAccessInput!): RequestAccessResult
          verifyAccessToken(roomNumber: String!, guestId: String!, token: String!): VerifyTokenResult
        }

        type Query {
          getGuest(roomNumber: String!, guestId: String!): Guest
          listGuestsByRoom(roomNumber: String!): [Guest]
          listGuests: [Guest]
        }

  GuestTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: guestcheckintable
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt AppSyncDynamoDBRole.Arn
      DynamoDBConfig:
        TableName: !Ref GuestTable
        AwsRegion: !Ref AWS::Region

  # AppSync が Lambda を呼び出すためのロール（Lambda Invoke許可）
  AppSyncLambdaRole:
    Condition: DoLambdaIntegration
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InvokeLambdaForAppSync
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - lambda:InvokeFunction
                Resource:
                  - !ImportValue Obw-RequestAccessFunctionArn
                  - !ImportValue Obw-VerifyAccessTokenFunctionArn

  RequestAccessLambdaDataSource:
    Condition: DoLambdaIntegration
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: requestAccessLambda
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !ImportValue Obw-RequestAccessFunctionArn

  VerifyAccessTokenLambdaDataSource:
    Condition: DoLambdaIntegration
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      Name: verifyAccessTokenLambda
      Type: AWS_LAMBDA
      ServiceRoleArn: !GetAtt AppSyncLambdaRole.Arn
      LambdaConfig:
        LambdaFunctionArn: !ImportValue Obw-VerifyAccessTokenFunctionArn

  AppSyncDynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  CreateGuestResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: createGuest
      DataSourceName: !GetAtt GuestTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "PutItem",
          "key": {
            "roomNumber": $util.dynamodb.toDynamoDBJson($ctx.args.input.roomNumber),
            "guestId": $util.dynamodb.toDynamoDBJson($ctx.args.input.guestId)
          },
          "attributeValues": {
            "guestId": $util.dynamodb.toDynamoDBJson($ctx.args.input.guestId),
            "guestName": $util.dynamodb.toDynamoDBJson($ctx.args.input.guestName),
            "email": $util.dynamodb.toDynamoDBJson($ctx.args.input.email),
            "address": $util.dynamodb.toDynamoDBJson($ctx.args.input.address),
            "phone": $util.dynamodb.toDynamoDBJson($ctx.args.input.phone),
            "occupation": $util.dynamodb.toDynamoDBJson($ctx.args.input.occupation),
            "nationality": $util.dynamodb.toDynamoDBJson($ctx.args.input.nationality),
            "passportImageUrl": $util.dynamodb.toDynamoDBJson($ctx.args.input.passportImageUrl),
            "checkInDate": $util.dynamodb.toDynamoDBJson($ctx.args.input.checkInDate),
            "checkOutDate": $util.dynamodb.toDynamoDBJson($ctx.args.input.checkOutDate),
            "approvalStatus": $util.dynamodb.toDynamoDBJson("waitingForPassportImage"),
            "createdAt": $util.dynamodb.toDynamoDBJson($util.time.nowISO8601()),
            "updatedAt": $util.dynamodb.toDynamoDBJson($util.time.nowISO8601()),
            "promoConsent": $util.dynamodb.toDynamoDBJson($ctx.args.input.promoConsent)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)

  UpdateGuestResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: updateGuest
      DataSourceName: !GetAtt GuestTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "UpdateItem",
          "key": {
            "roomNumber": $util.dynamodb.toDynamoDBJson($ctx.args.input.roomNumber),
            "guestId": $util.dynamodb.toDynamoDBJson($ctx.args.input.guestId)
          },
          "update": {
            "expression": "SET #updatedAt = :updatedAt, #approvalStatus = :approvalStatus, #passportImageUrl = :passportImageUrl",
            "expressionNames": {
              "#updatedAt": "updatedAt",
              "#approvalStatus": "approvalStatus",
              "#passportImageUrl": "passportImageUrl"
            },
            "expressionValues": {
              ":updatedAt": $util.dynamodb.toDynamoDBJson($util.time.nowISO8601()),
              ":approvalStatus": $util.dynamodb.toDynamoDBJson($ctx.args.input.approvalStatus),
              ":passportImageUrl": $util.dynamodb.toDynamoDBJson($ctx.args.input.passportImageUrl)
            }
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)

  GetGuestResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: getGuest
      DataSourceName: !GetAtt GuestTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "GetItem",
          "key": {
            "roomNumber": $util.dynamodb.toDynamoDBJson($ctx.args.roomNumber),
            "guestId": $util.dynamodb.toDynamoDBJson($ctx.args.guestId)
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)

  ListGuestsResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listGuests
      DataSourceName: !GetAtt GuestTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Scan"
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result.items)

  ListGuestsByRoomResolver:
    Type: AWS::AppSync::Resolver
    DependsOn: AppSyncSchema
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Query
      FieldName: listGuestsByRoom
      DataSourceName: !GetAtt GuestTableDataSource.Name
      RequestMappingTemplate: |
        {
          "version": "2017-02-28",
          "operation": "Query",
          "query": {
            "expression": "roomNumber = :roomNumber",
            "expressionValues": {
              ":roomNumber": $util.dynamodb.toDynamoDBJson($ctx.args.roomNumber)
            }
          }
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result.items)

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: true

  UnauthRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Federated: cognito-identity.amazonaws.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                "cognito-identity.amazonaws.com:aud": !Ref IdentityPool
              "ForAnyValue:StringLike":
                "cognito-identity.amazonaws.com:amr": unauthenticated
      Policies:
        - PolicyName: AppSyncPublicAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - appsync:GraphQL
                Resource: "*"

  IdentityPoolRoleAttachment:
    Type: AWS::Cognito::IdentityPoolRoleAttachment
    Properties:
      IdentityPoolId: !Ref IdentityPool
      Roles:
        unauthenticated: !GetAtt UnauthRole.Arn

  RequestAccessResolver:
    Condition: DoLambdaIntegration
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: requestAccess
      DataSourceName: !Ref RequestAccessLambdaDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "Invoke",
          "payload": $util.toJson($ctx.args)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)

  VerifyAccessTokenResolver:
    Condition: DoLambdaIntegration
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt AppSyncApi.ApiId
      TypeName: Mutation
      FieldName: verifyAccessToken
      DataSourceName: !Ref VerifyAccessTokenLambdaDataSource
      RequestMappingTemplate: |
        {
          "version": "2018-05-29",
          "operation": "Invoke",
          "payload": $util.toJson($ctx.args)
        }
      ResponseMappingTemplate: |
        $util.toJson($ctx.result)

Outputs:
  ApiEndpoint:
    Description: "AppSync API Endpoint"
    Value: !GetAtt AppSyncApi.GraphQLUrl
  CognitoIdentityPoolId:
    Description: "Cognito Identity Pool ID"
    Value: !Ref IdentityPool
  GuestTableName:
    Description: "DynamoDB guest table name"
    Value: !Ref GuestTable
    Export:
      Name: Obw-GuestTableName