name: Daily Actions Deployment

on:
  push:
    branches: [main, feature/*]
    paths:
      - 'lambda_functions/daily_records_cleanup/**'
      - '.github/workflows/daily-actions.yml'
      - 'template-daily-actions.yaml'
  workflow_dispatch:

jobs:
  deploy-daily-cleanup:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: obw-daily-cleanup
      cancel-in-progress: false

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: SAM build
        run: sam build --template-file template-daily-actions.yaml

      - name: SAM deploy
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name obw-daily-cleanup \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \