name: Deploy SAM Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: SAM Build
        run: sam build --use-container

      - name: SAM Deploy
        env:
          OPENAI_API_KEY_FROM_SECRET: ${{ secrets.OPENAI_API_KEY }}
          TWILIO_ACCOUNT_SID_FROM_SECRET: ${{ secrets.TWILIO_ACCOUNT_SID }}
          TWILIO_AUTH_TOKEN_FROM_SECRET: ${{ secrets.TWILIO_AUTH_TOKEN }}
        run: |
          sam deploy \
            --stack-name obw-ai-lambda \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --parameter-overrides \
              OpenAiApiKey="$OPENAI_API_KEY_FROM_SECRET" \
              TwilioAccountSid="$TWILIO_ACCOUNT_SID_FROM_SECRET" \
              TwilioAuthToken="$TWILIO_AUTH_TOKEN_FROM_SECRET"

      - name: Get Immediate Response Function URL from Alias
        id: get_function_url
        run: |
          # エイリアス "live" 経由の Function URL を取得します
          FUNCTION_URL=$(aws lambda get-function-url-config --function-name obw-immediate-response-function:live --query 'FunctionUrl' --output text)
          echo "Function URL is: ${FUNCTION_URL}"
          echo "::set-output name=function_url::${FUNCTION_URL}"
      
      - name: Update CloudFormation Stack with Function URL
        run: |
          echo "Updating stack with ImmediateResponseFunctionUrlParam=${{ steps.get_function_url.outputs.function_url }}"
          aws cloudformation update-stack \
            --stack-name obw-ai-lambda \
            --use-previous-template \
            --capabilities CAPABILITY_IAM \
            --parameters ParameterKey=ImmediateResponseFunctionUrlParam,ParameterValue="${{ steps.get_function_url.outputs.function_url }}" \
                         ParameterKey=OpenAiApiKey,ParameterValue="$OPENAI_API_KEY_FROM_SECRET" \
                         ParameterKey=TwilioAccountSid,ParameterValue="$TWILIO_ACCOUNT_SID_FROM_SECRET" \
                         ParameterKey=TwilioAuthToken,ParameterValue="$TWILIO_AUTH_TOKEN_FROM_SECRET"
          aws cloudformation wait stack-update-complete --stack-name obw-ai-lambda
