name: Deploy SAM Application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: SAM Build
        run: sam build --use-container
        # working-directory: ${{ github.workspace }} # プロジェクトルートで実行

      - name: SAM Deploy
        env:
          # OPENAI_API_KEY_SECRET という名前でGitHub Secretから読み込む
          # GitHub Secretの名前は OPENAI_API_KEY とすることを推奨
          OPENAI_API_KEY_FROM_SECRET: ${{ secrets.OPENAI_API_KEY }}
        run: |
          sam deploy \
            --stack-name obw-ai-lambda \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm \
            --parameter-overrides OpenAiApiKey="$OPENAI_API_KEY_FROM_SECRET"
        # working-directory: ${{ github.workspace }} # プロジェクトルートで実行
