name: Deploy Infrastructure

on:
  # workflow_run: # 本番ではコメントアウト外して、Lambdaのデプロイが完了したら実行
  #   workflows: ["Deploy Lambda Functions"]
  #   types: [completed]
  push:
    branches: [main, feature/*] # 本番では main ブランチを使用
    paths:
      - 'obw_react_app/infrastructure/cloudformation.yaml'
      - '.github/workflows/infra-appsync.yml'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: obw-appsync-stack
      cancel-in-progress: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Validate CloudFormation template
        run: aws cloudformation validate-template --template-body file://obw_react_app/infrastructure/cloudformation.yaml

      - name: Deploy CloudFormation stack (AppSync dynamic)
        run: |
          set -e
          COUNT=$(aws cloudformation list-exports \
            --query "length(Exports[?Name=='Obw-RequestAccessFunctionArn' || Name=='Obw-VerifyAccessTokenFunctionArn' || Name=='Obw-GetPresignedUrlFunctionArn'])" \
            --output text || echo 0)
          if [ "$COUNT" -ge 3 ]; then FLAG=true; else FLAG=false; fi
          echo "EnableLambdaIntegration=${FLAG}"
          aws cloudformation deploy \
            --template-file obw_react_app/infrastructure/cloudformation.yaml \
            --stack-name obw-appsync-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EnableLambdaIntegration=${FLAG} \
            --no-fail-on-empty-changeset

      - name: Show stack events on failure
        if: failure()
        run: aws cloudformation describe-stack-events --stack-name obw-appsync-stack --max-items 50

      - name: List AppSync data sources (debug)
        run: |
          API_ID=$(aws cloudformation describe-stacks --stack-name obw-appsync-stack \
            --query "Stacks[0].Outputs[?OutputKey=='AppSyncApiId'].OutputValue" --output text)
          aws appsync list-data-sources --api-id "$API_ID"
