name: Deploy Infrastructure

on:
  # workflow_run: # 本番ではコメントアウト外して、Lambdaのデプロイが完了したら実行
  #   workflows: ["Deploy Lambda Functions"]
  #   types: [completed]
  push:
    branches: [main, feature/magic-link-access] # 本番では main ブランチを使用
    paths:
      - 'obw_react_app/infrastructure/cloudformation.yaml'
      - '.github/workflows/infra-appsync.yml'
  workflow_dispatch:

jobs:
  deploy-infra:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Deploy CloudFormation stack (AppSync base)
        run: |
          aws cloudformation deploy \
            --template-file obw_react_app/infrastructure/cloudformation.yaml \
            --stack-name obw-appsync-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EnableLambdaIntegration=false \
            --no-fail-on-empty-changeset
