name: Deploy Lambda Functions

on:
  push:
    branches: [main, feature/*]
    paths:
      - 'lambda_functions/admin_approve_guest/**'
      - 'lambda_functions/get_presigned_url/**'
      - 'lambda_functions/notify_admin/**'
      - 'lambda_functions/request_access/**'
      - 'lambda_functions/verify_access/**'
      - '.github/workflows/lambda-deploy.yml'
      - 'template-lambdas.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    concurrency:
      group: obw-appsync-stack
      cancel-in-progress: false

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Checkout ServerlessResponseAPI repository
        uses: actions/checkout@v4
        with:
          repository: auditive-tokyo/ServerlessResponseAPI
          ref: OBW-Customized
          path: external/ServerlessResponseAPI

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ap-northeast-1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Build ServerlessResponseAPI Lambda (TypeScript)
        run: |
          cd external/ServerlessResponseAPI
          npm install
          npm run build

      - name: Build ServerlessResponseAPI Layer (Node.js)
        run: |
          cd external/ServerlessResponseAPI/layer
          npm install

      - name: Install AWS SAM CLI
        run: pip install aws-sam-cli

      - name: Ensure AppSync base stack exists (EnableLambdaIntegration=false)
        run: |
          set -e
          if ! aws cloudformation describe-stacks --stack-name obw-appsync-stack >/dev/null 2>&1; then
            echo "obw-appsync-stack not found. Deploying base stack..."
            aws cloudformation deploy \
              --template-file obw_react_app/infrastructure/cloudformation.yaml \
              --stack-name obw-appsync-stack \
              --capabilities CAPABILITY_NAMED_IAM \
              --parameter-overrides EnableLambdaIntegration=false \
              --no-fail-on-empty-changeset
          else
            echo "obw-appsync-stack exists. Skipping base deploy."
          fi

      - name: Force disable Lambda integration in AppSync (idempotent)
        run: |
          aws cloudformation deploy \
            --template-file obw_react_app/infrastructure/cloudformation.yaml \
            --stack-name obw-appsync-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EnableLambdaIntegration=false \
            --no-fail-on-empty-changeset

      - name: Get GuestTableName from CloudFormation (Outputs or Exports)
        id: get_guest_table_name
        run: |
          set -e
          GUEST_TABLE_NAME=$(aws cloudformation describe-stacks \
            --stack-name obw-appsync-stack \
            --query "Stacks[0].Outputs[?OutputKey=='GuestTableName'].OutputValue" \
            --output text || true)

          if [ -z "$GUEST_TABLE_NAME" ] || [ "$GUEST_TABLE_NAME" = "None" ]; then
            echo "Outputs not found. Trying Exports (Obw-GuestTableName)..."
            GUEST_TABLE_NAME=$(aws cloudformation list-exports \
              --query "Exports[?Name=='Obw-GuestTableName'].Value" \
              --output text || true)
          fi

          if [ -z "$GUEST_TABLE_NAME" ] || [ "$GUEST_TABLE_NAME" = "None" ]; then
            echo "GuestTableName not found. Ensure cloudformation.yaml has Outputs.GuestTableName and stack deployed." >&2
            exit 1
          fi

          echo "GuestTableName is $GUEST_TABLE_NAME"
          echo "guest_table_name=$GUEST_TABLE_NAME" >> $GITHUB_OUTPUT

      - name: SAM Build
        run: sam build --use-container --template-file template-lambdas.yaml

      - name: SAM Deploy
        env:
          TELEGRAM_BOT_TOKEN_FROM_SECRET: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID_FROM_SECRET: ${{ secrets.TELEGRAM_CHAT_ID }}
          SENDGRID_API_KEY_FROM_SECRET: ${{ secrets.SENDGRID_API_KEY }}
        run: |
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name obw-lambda-functions \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --parameter-overrides \
              GuestTableName="${{ steps.get_guest_table_name.outputs.guest_table_name }}" \
              TelegramBotTokenParam="$TELEGRAM_BOT_TOKEN_FROM_SECRET" \
              TelegramChatIdParam="$TELEGRAM_CHAT_ID_FROM_SECRET" \
              SendGridApiKey="$SENDGRID_API_KEY_FROM_SECRET" \
            --no-fail-on-empty-changeset

      - name: Wait for Lambda exports (Function ARNs)
        run: |
          set -e
          for i in {1..15}; do
            COUNT=$(aws cloudformation list-exports \
              --query "length(Exports[?Name=='Obw-RequestAccessFunctionArn' || Name=='Obw-VerifyAccessTokenFunctionArn' || Name=='Obw-GetPresignedUrlFunctionArn' || Name=='Obw-AdminApproveGuestFunctionArn'])" \
              --output text || echo 0)
            if [ "$COUNT" -ge 4 ]; then
              echo "All Lambda exports found."
              break
            fi
            echo "Waiting for Lambda exports... ($i/15)"
            sleep 6
          done

      - name: Wait until AppSync stack is idle
        run: |
          for i in {1..20}; do
            STATUS=$(aws cloudformation describe-stacks --stack-name obw-appsync-stack --query "Stacks[0].StackStatus" --output text || echo "")
            echo "AppSync stack status: $STATUS"
            if [[ "$STATUS" != *"_IN_PROGRESS" ]]; then break; fi
            sleep 9
          done

      - name: Enable Lambda integration in AppSync
        run: |
          aws cloudformation deploy \
            --template-file obw_react_app/infrastructure/cloudformation.yaml \
            --stack-name obw-appsync-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EnableLambdaIntegration=true \
            --no-fail-on-empty-changeset

      - name: Get Immediate Response Function URL from Alias
        id: get_function_url
        run: |
          # エイリアス "live" 経由の Function URL を取得します
          FUNCTION_URL=$(aws lambda get-function-url-config --function-name obw-immediate-response-function:live --query 'FunctionUrl' --output text)
          echo "Function URL is: ${FUNCTION_URL}"
          echo "function_url=${FUNCTION_URL}" >> $GITHUB_OUTPUT
      
      - name: Update CloudFormation Stack with Function URL 
        env:
          TELEGRAM_BOT_TOKEN_FROM_SECRET: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID_FROM_SECRET: ${{ secrets.TELEGRAM_CHAT_ID }}
          SENDGRID_API_KEY_FROM_SECRET: ${{ secrets.SENDGRID_API_KEY }}  # ← 追加
        run: |
          echo "Updating stack with ImmediateResponseFunctionUrlParam=${{ steps.get_function_url.outputs.function_url }}"

          # sam deploy を再度実行して、Function URL をパラメータとして渡す
          sam deploy \
            --template-file .aws-sam/build/template.yaml \
            --stack-name obw-lambda-functions \
            --capabilities CAPABILITY_IAM \
            --resolve-s3 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              ImmediateResponseFunctionUrlParam="${{ steps.get_function_url.outputs.function_url }}" \
              OpenAiApiKey="$OPENAI_API_KEY_FROM_SECRET" \
              OpenAiVectorStoreId="$OPENAI_VECTOR_STORE_ID_FROM_SECRET" \
              TwilioAccountSid="$TWILIO_ACCOUNT_SID_FROM_SECRET" \
              TwilioAuthToken="$TWILIO_AUTH_TOKEN_FROM_SECRET" \
              TelegramBotTokenParam="$TELEGRAM_BOT_TOKEN_FROM_SECRET" \
              TelegramChatIdParam="$TELEGRAM_CHAT_ID_FROM_SECRET" \
              SendGridApiKey="$SENDGRID_API_KEY_FROM_SECRET"
